### ISSUE TITLE
Could not pass event BlockPlaceEvent

### ISSUE THREAD

**Issue by TheChampTF** [FallenYouth/FlashlightPlus#3]
Running git-Bukkit-0899683 (MC: 1.8)

Could not pass event BlockPlaceEvent to FlashlightPlus v1.0.6 http://paste.yu8.me/?5ff1588f77151285#imyDMSd+1mpiUipNGAN6GBKRxDnhjryX2rmYaKuI97k=

**Comment by FallenYouth** [comment]
Looking into this issue now.

**Comment by FallenYouth** [comment]
Updated plugin to version 1.0.7, this should be a fix. I wasnt sure what the issue was and how it was happening but hopefully this will be a fix. I will leave this issue open just in case there is an issue that needs to be fixed

FlashlightPlus 1.0.7: http://www.spigotmc.org/resources/flashlightplus.262/download?version=9519
